name: Terraform Module Dependencies

on:
  push:
    branches:
      - main

jobs:
  terradepend:
    runs-on: ubuntu-latest
    name: "Check that current module version references are current."
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: execute py script
        run: |
          pip install requests
          python terradepend.py
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          add-paths: |
            *.tf