name: Terraform Testing

on: [pull_request]

jobs:
  deploy:
      name: Terraform
      runs-on: ubuntu-latest
      # These permissions are needed to interact with GitHub's OIDC Token endpoint.
      permissions:
        id-token: write
        contents: read
      steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Configure Git to use Personal Access Token
        run: |
          git config --global url."https://${{ secrets.PAT_TOKEN }}@github.com/".insteadOf "https://github.com/"

      - name: Run Terraform Init
        run: |
          terraform init

      - name: Run Terraform Plan
        run: |
          terraform plan -out current.tfplan

      - name: Run Terraform Apply
        run: |
          terraform apply current.tfplan

      - name: Run Terraform Destroy
        if: always()
        run: |
          terraform destroy -auto-approve